server:
  port: 9090
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
  profiles:
    active: dev
  application:
    name: identity-server
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8071