spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080
  application:
    name: identity-server
  config:
    import: "configserver:"
  cloud:
    config:
      uri: "http://localhost:8071"
  profiles:
    active: dev

logging:
  level:
    org:
      springframework:
        security: DEBUG