spring:
  profiles:
    active: dev
  application:
    name: gateway-server
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8071
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always